import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertInMoeda1700671873570 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('1', 'ZAR', 'Rand');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('2', 'AON', 'Novo Kuanza');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('3', 'DZD', 'Dinar Argelino');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('4', 'BWP', 'Pula');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('5', 'BIF', 'Franco do Burundi');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('6', 'CVE', 'Escudo do Cabo Verde');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('7', 'KMF', 'Franco Comorense');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('8', 'ZRN', 'Novo Zaire');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('9', 'BUA', 'Franco CFA');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('10', 'DJF', 'Franco do Djibuti');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('11', 'EGP', 'Libra Egípcia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('12', 'ERN', 'Nakfa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('13', 'ETB', 'Birr');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('14', 'GMD', 'Dalasi');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('15', 'GHC', 'Cedi Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('16', 'GWP', 'Peso');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('17', 'GNF', 'Franco CFA');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('18', 'LSL', 'Loti');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('19', 'LRD', 'Dólar Liberiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('20', 'LYD', 'Dinar Líbio');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('21', 'MGF', 'Franco Malgaxe');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('22', 'MWK', 'Cuacha Malauiana');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('23', 'MAD', 'Dirrã Marroquino');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('24', 'MUR', 'Rupia Mauriciana');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('25', 'MZM', 'Metical');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('26', 'NAD', 'Dólar Namibiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('27', 'NGN', 'Naira');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('28', 'KES', 'Xelim Queniano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('29', 'RWF', 'Franco de Ruanda');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('30', 'SHP', 'Libra');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('31', 'STD', 'Dobra');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('32', 'SLL', 'Leone');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('33', 'SCR', 'Rupia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('34', 'SOS', 'Xelim Somaliano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('35', 'SZL', 'Lilangeni');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('36', 'TZS', 'Libra Sudanesa / Dinar Sudanês');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('37', 'TZS', 'Xelim Tanzaniano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('38', 'TND', 'Dinar Tunisiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('39', 'UGX', 'Novo Xelim de Uganda');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('40', 'ZMK', 'Cuacha Zambiana');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('41', 'ZWD', 'Dólar Zimbabuano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('42', 'ANG', 'Florim');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('43', 'AWG', 'Florim');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('44', 'BSD', 'Dólar das Bahamas');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('45', 'BZD', 'Dólar de Belize');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('46', 'BBD', 'Dólar Barbados');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('47', 'BMD', 'Dólar Bermudas');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('48', 'KYD', 'Dólar Cayman');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('49', 'CRC', 'Colón Costarriquenho');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('50', 'CUP', 'Peso Cubano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('51', 'SVC', 'Colón Salvadorenho');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('52', 'GTQ', 'Quetzal');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('53', 'HTG', 'Gourde');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('54', 'HNL', 'Lempira');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('55', 'JMD', 'Dólar Jamaicano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('56', 'MXN', 'Peso Mexicano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('57', 'NIO', 'Córdoba Ouro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('58', 'PAB', 'Balboa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('59', 'DOP', 'Peso Dominicano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('60', 'CAD', 'Dólar Canadense');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('61', 'USD', 'Dólar Americano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('62', 'ARS', 'Peso Argentino');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('63', 'BOB', 'Boliviano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('64', 'BRL', 'Real');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('65', 'CLP', 'Peso Chileno');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('66', 'COP', 'Peso Colombiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('67', 'ECS', 'Sucre');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('68', 'FKP', 'Libra');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('69', 'GYD', 'Dólar Guianense');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('70', 'PYG', 'Guarani');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('71', 'PEN', 'Sol Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('72', 'SRG', 'Florim do Suriname');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('73', 'TTD', 'Dólar de Trinidad e Tobago');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('74', 'UYU', 'Peso Uruguaio');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('75', 'VEB', 'Bolívar');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('76', 'AFA', 'Afegani');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('77', 'SAR', 'Rial Saudita');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('78', 'AMD', 'Dram');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('79', 'AZM', 'Manat Azerbaidjano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('80', 'BDT', 'Taka');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('81', 'BHD', 'Dinar de Barein');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('82', 'BND', 'Dólar de Brunei');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('83', 'BTN', 'Ngultrum');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('84', 'KHR', 'Riel');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('85', 'QAR', 'Rial de Catar');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('86', 'KZT', 'Tenge');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('87', 'CNY', 'Iuan');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('88', 'CYP', 'Libra Cipriota / Lira Turca');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('89', 'SGD', 'Dólar de Cingapura');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('90', 'KPW', 'Won Norte-Coreana');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('91', 'KRW', 'Won Sul-Coreano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('92', 'AED', 'Dirrã');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('93', 'RUB', 'Rublo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('94', 'PHP', 'Peso Filipino');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('95', 'GEL', 'Lari');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('96', 'HKD', 'Dólar de Hong Kong');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('97', 'YER', 'Rial Iemenita');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('98', 'INR', 'Rupia Indiana');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('99', 'IDR', 'Rupia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('100', 'IRR', 'Rial Iraniano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('101', 'IQD', 'Dinar Iraquiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('102', 'ILS', 'Shekel Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('103', 'JPY', 'Iene');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('104', 'JOD', 'Dinar Jordaniano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('105', 'KWD', 'Dinar Kuweitiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('106', 'LAK', 'Kip Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('107', 'LBP', 'Libra Libanesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('108', 'MOP', 'Pataca');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('109', 'MYR', 'Ringgit Malaio');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('110', 'MVR', 'Rufia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('111', 'MMK', 'Quiat');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('112', 'MNT', 'Tugrik');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('113', 'NPR', 'Rupia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('114', 'OMR', 'Rial');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('115', 'PKR', 'Rupia Paquistanesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('116', 'PGK', 'Kina');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('117', 'SBD', 'Dólar de Salomão');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('118', 'SYP', 'Libra Síria');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('119', 'LKR', 'Rupia Cingalesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('120', 'TJR', 'Rublo Tadjique');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('121', 'THB', 'Baht');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('122', 'TWD', 'Novo Dólar de Taiwan');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('123', 'TRL', 'Lira Turca');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('124', 'UZS', 'Sum');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('125', 'VND', 'Dongue Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('126', 'ALL', 'Lek Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('127', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('128', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('129', 'BYB', 'Rublo Bielo-Russo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('130', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('131', 'BAM', 'Marco Conversível');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('132', 'BGN', 'Lev Novo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('133', 'HRK', 'Kuna');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('134', 'DKK', 'Coroa Dinamarquesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('135', 'SKK', 'Coroa Eslováquia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('136', 'SIT', 'Tolar');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('137', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('138', 'EEK', 'Coroa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('139', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('140', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('141', 'GIP', 'Libra');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('142', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('143', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('144', 'HUF', 'Forint');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('145', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('146', 'ISK', 'Nova Coroa Islandesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('147', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('148', 'LVL', 'Lats');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('149', 'LTL', 'Litas');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('150', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('151', 'MKD', 'Novo Denar Macedônio');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('152', 'MTL', 'Lira Maltesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('153', 'MDL', 'Leu');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('154', 'NOK', 'Coroa Norueguesa');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('155', 'PZN', 'Zloty');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('156', 'EUR', 'Euro');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('157', 'GBP', 'Libra Esterlina');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('158', 'CZK', 'Coroa Tcheca');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('159', 'ROL', 'Leu Romeno');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('160', 'SEK', 'Coroa Sueca');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('161', 'CHF', 'Franco Suíço');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('162', 'UAH', 'Hryvna');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('163', 'AUD', 'Dólar Australiano');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('164', 'FJD', 'Dólar de Fiji');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('165', 'NZD', 'Dólar da Nova Zelândia');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('166', 'WST', 'Tala');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('167', 'TOP', 'Paanga');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('168', 'TPE', 'Escudo');
            INSERT INTO moeda ("id", "codigo", "nome") VALUES ('169', 'VUV', 'Vatu');        
        `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`
              DELETE FROM public.moeda;
          `);
  }
}
